spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  jackson:
    time-zone: UTC
  devtools:
    add-properties: false
jwt:
  secret: ${JWT_SECRET}
  expirationTime: 3600
server:
  port: 8080
  servlet:
    context-path: /auth/v1